services:
  db:
    image: mysql
    container_name: springapi-db
    env_file:
      - .env
    volumes:
      - springapi-db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306

volumes:
  springapi-db:
    driver: local
